# action.yml
name: 'Recurring Issue Creator'
description: |
  This action re-creates/copies an issue
inputs:
  label:
    description: label to lookup for (repeat daily, repeat monthly, etc.)
    required: true
  frequency:
    description: frequency of reoccurance (1d,1w,1m,3m,1y,etc)
    required: true
outputs:
  issues:
    description: Issues selected for re-creation
runs:
  using: 'node12'
  main: 'dist/index.js'

