on:
  push:
    branches:
      - "main"
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release on Tagging

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

  push:
    name: Push Docker Image to Github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Github Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/yogendra/recurring-issue-creator-github-action:${{ github.ref }}
            ghcr.io/yogendra/recurring-issue-creator-github-action:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

