on: 
  push:
    branches:
      - "main"
name: Testing my flow on push 
jobs:
  daily:
    runs-on: ubuntu-latest
    name: Create daily issues    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: create
      id: create
      uses: ./
      with:
        label: 'repeat daily'
        frequency: 1d
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.create.outputs.issues }}"
